# Generated by Django 2.2.4 on 2019-08-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('link', models.URLField()),
                ('read', models.BooleanField()),
                ('watch', models.BooleanField()),
            ],
        ),
    ]
